function score = get_patient_exp_score(dataName)
%GET_PATIENT_EXP_SCORE This function gets the patient's visual
%   assessment score to be decided by experts.   
%
%   Author: Osman Baskaya
%   Date: 03/08/2012

score = -1; % initial. score should not be -1.

%% Experts' Scores

% Bu score'lar 
% DemansSkalalama/Bayındır grubu/sulcus mr4tek.doc ve
% DemansSkalalama/Demans_DataRatings_BAHUN betul_ORJİNAL.xls
% dosyalarindan alindi.


patients = {
            {'baharpelin', 1}, ...
            {'nesrinirgi', 2} ...
            {'alidemir', 3} ...
            {'mahirerburhan', 4}, ...
            {'turgut', 5} ...
            {'ozlemaliyilmaz', 6} ...
            {'erdalayhan', 7} ...
            {'turkangencoglu', 8} ...
            {'orsalir', 6}, ...
            {'baysal', 5} ...
            {'faizesuel', 4} ...
            {'halise', 1}, ...
            {'savas', 6} ... %mustafa carik savas? kontrol et
            {'servetdemirel', 1} ...
            {'sonat', 6} ...
            {'akdogan', 4} ...  
            {'bayraktaroglu', 5}, ...
            {'citoglu', 4} ...
            {'dalbudak', 6} ...
            {'eyupoglu', 7}, ... % Demans Sonuclarinda eyuboglu diye geciyor.
            {'haciahmetoglu', 6} ...
            {'kamileisik', 7} ...
            {'koseoglu', 8} ...
            {'nuranaydinoglu', 2} ...            
            {'sevim', 5} ... %necla sevim 
            {'yildirim', 5} ...            
            {'yilmaz', 7} ... %ertan yılmaz
            {'yukselilk', 5} ...
            {'cumbul', 6}
            %{'alidemir', 3} ...
          };

%% Check the patient's score.

for k=1:length(patients)
    [patient_name, patient_score] = patients{k}{:}; 
    if strfind(dataName, patient_name)
        score = patient_score;
        break;
    end
end

%% Check some Error

%If the patient is not our patients list. Error will be occured.
if score == -1
    error('Patient %s is not in our patient score list. Please add it.', dataName)
end


end